In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [16]:
df = pd.read_csv('training data.csv')

<ipython-input-16-291cd5c12d1c>:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('training data.csv')

In [17]:
df.head()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z97,v97,x98,y98,z98,v98,x99,y99,z99,v99
0,Forward Fold,0.553503,0.589154,-0.053227,0.999848,0.551295,0.617827,-0.098426,0.999913,0.550036,...,0.316258,0.254633,0.504816,0.938543,-0.119085,0.814447,0.494917,0.930861,0.213300,0.267587
1,Forward Fold,0.55378,0.589641,-0.054581,0.999849,0.551513,0.618255,-0.100107,0.999914,0.550228,...,0.317192,0.255281,0.504461,0.938518,-0.119699,0.814630,0.494285,0.930849,0.213712,0.267646
2,Forward Fold,0.554106,0.5904,-0.0561,0.999849,0.551763,0.618992,-0.101833,0.999914,0.550453,...,0.317138,0.256015,0.498611,0.938076,-0.121977,0.814902,0.493554,0.930860,0.213213,0.267919
3,Forward Fold,0.554537,0.591136,-0.056402,0.99985,0.552081,0.619783,-0.102108,0.999915,0.550742,...,0.317088,0.256472,0.495591,0.937631,-0.122727,0.815257,0.492875,0.930846,0.212855,0.267988
4,Forward Fold,0.554774,0.591698,-0.057988,0.99985,0.552234,0.62037,-0.103818,0.999915,0.550885,...,0.316333,0.256812,0.494406,0.937293,-0.126726,0.815560,0.492563,0.930834,0.211536,0.267697

In [18]:
df.tail()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z97,v97,x98,y98,z98,v98,x99,y99,z99,v99
12102,Warrior Pose 1,0.491516292095184,0.285143971443176,-0.042039506137371,0.999784648418427,0.498440861701965,0.267713904380798,-0.057457260787487,0.999825537204742,0.501198887825012,...,0.050077,0.984586,0.689151,0.949904,-0.017940,0.958340,0.313776,0.946884,-0.018688,0.973341
12103,Warrior Pose 1,0.491522043943405,0.285139113664627,-0.04204461351037,0.999784350395203,0.498446673154831,0.267707735300064,-0.05746141821146,0.999825239181519,0.50120609998703,...,0.050074,0.984596,0.689157,0.949896,-0.017980,0.958293,0.313779,0.946893,-0.018691,0.973335
12104,Warrior Pose 1,0.491524904966354,0.285133302211761,-0.0420754365623,0.99978369474411,0.498449623584747,0.267700165510178,-0.057488244026899,0.999824583530426,0.501209199428558,...,0.050078,0.984610,0.689176,0.949889,-0.018310,0.958293,0.313783,0.946910,-0.018693,0.973337
12105,Warrior Pose 1,0.491530805826187,0.285128355026245,-0.042072892189026,0.999783277511597,0.498456090688705,0.267695069313049,-0.05748587474227,0.999824225902557,0.5012167096138,...,0.050116,0.984613,0.689187,0.949883,-0.018579,0.958245,0.313786,0.946928,-0.018657,0.973302
12106,Warrior Pose 1,0.49153333902359,0.285123467445374,-0.042051568627358,0.999782800674439,0.498458355665207,0.267689555883408,-0.05746291577816,0.999823749065399,0.501219213008881,...,0.050101,0.984616,0.689213,0.949862,-0.018611,0.958168,0.313790,0.946948,-0.018691,0.973268

In [19]:
df.columns

Index(['class', 'x1', 'y1', 'z1', 'v1', 'x2', 'y2', 'z2', 'v2', 'x3',
       ...
       'z97', 'v97', 'x98', 'y98', 'z98', 'v98', 'x99', 'y99', 'z99', 'v99'],
      dtype='object', length=397)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12107 entries, 0 to 12106
Columns: 397 entries, class to v99
dtypes: float64(96), object(301)
memory usage: 36.7+ MB

In [21]:
X = df.drop('class', axis=1) # features
y = df['class'] # target value

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)

In [23]:
y_test

5668     Warrior Pose 2
12088    Warrior Pose 1
2137      Mountain Fold
11254    Warrior Pose 1
8476     Warrior Pose 2
              ...
1733      Mountain Fold
9594     Warrior Pose 1
5996     Warrior Pose 2
10487    Warrior Pose 1
4398     Warrior Pose 3
Name: class, Length: 3633, dtype: object

In [24]:
X

,x1,y1,z1,v1,x2,y2,z2,v2,x3,y3,...,z97,v97,x98,y98,z98,v98,x99,y99,z99,v99
0,0.553503,0.589154,-0.053227,0.999848,0.551295,0.617827,-0.098426,0.999913,0.550036,0.620351,...,0.316258,0.254633,0.504816,0.938543,-0.119085,0.814447,0.494917,0.930861,0.213300,0.267587
1,0.55378,0.589641,-0.054581,0.999849,0.551513,0.618255,-0.100107,0.999914,0.550228,0.620777,...,0.317192,0.255281,0.504461,0.938518,-0.119699,0.814630,0.494285,0.930849,0.213712,0.267646
2,0.554106,0.5904,-0.0561,0.999849,0.551763,0.618992,-0.101833,0.999914,0.550453,0.621518,...,0.317138,0.256015,0.498611,0.938076,-0.121977,0.814902,0.493554,0.930860,0.213213,0.267919
3,0.554537,0.591136,-0.056402,0.99985,0.552081,0.619783,-0.102108,0.999915,0.550742,0.622334,...,0.317088,0.256472,0.495591,0.937631,-0.122727,0.815257,0.492875,0.930846,0.212855,0.267988
4,0.554774,0.591698,-0.057988,0.99985,0.552234,0.62037,-0.103818,0.999915,0.550885,0.622947,...,0.316333,0.256812,0.494406,0.937293,-0.126726,0.815560,0.492563,0.930834,0.211536,0.267697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12102,0.491516292095184,0.285143971443176,-0.042039506137371,0.999784648418427,0.498440861701965,0.267713904380798,-0.057457260787487,0.999825537204742,0.501198887825012,0.266888946294785,...,0.050077,0.984586,0.689151,0.949904,-0.017940,0.958340,0.313776,0.946884,-0.018688,0.973341
12103,0.491522043943405,0.285139113664627,-0.04204461351037,0.999784350395203,0.498446673154831,0.267707735300064,-0.05746141821146,0.999825239181519,0.50120609998703,0.266880750656128,...,0.050074,0.984596,0.689157,0.949896,-0.017980,0.958293,0.313779,0.946893,-0.018691,0.973335
12104,0.491524904966354,0.285133302211761,-0.0420754365623,0.99978369474411,0.498449623584747,0.267700165510178,-0.057488244026899,0.999824583530426,0.501209199428558,0.266871899366379,...,0.050078,0.984610,0.689176,0.949889,-0.018310,0.958293,0.313783,0.946910,-0.018693,0.973337
12105,0.491530805826187,0.285128355026245,-0.042072892189026,0.999783277511597,0.498456090688705,0.267695069313049,-0.05748587474227,0.999824225902557,0.5012167096138,0.266865700483322,...,0.050116,0.984613,0.689187,0.949883,-0.018579,0.958245,0.313786,0.946928,-0.018657,0.973302
12106,0.49153333902359,0.285123467445374,-0.042051568627358,0.999782800674439,0.498458355665207,0.267689555883408,-0.05746291577816,0.999823749065399,0.501219213008881,0.2668596804142,...,0.050101,0.984616,0.689213,0.949862,-0.018611,0.958168,0.313790,0.946948,-0.018691,0.973268

In [25]:
y

0          Forward Fold
1          Forward Fold
2          Forward Fold
3          Forward Fold
4          Forward Fold
              ...
12102    Warrior Pose 1
12103    Warrior Pose 1
12104    Warrior Pose 1
12105    Warrior Pose 1
12106    Warrior Pose 1
Name: class, Length: 12107, dtype: object

In [26]:
from sklearn.pipeline import make_pipeline 
from sklearn.preprocessing import StandardScaler 

from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [27]:
# df.apply(LabelEncoder().fit_transform)

In [28]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

for i in range(0,df.shape[1]):
    if df.dtypes[i]=='object':
        df[df.columns[i]] = le.fit_transform(df[df.columns[i]])

TypeError: Encoders require their input to be uniformly strings or numbers. Got ['float', 'str']

In [ ]:
# #Fetch features of type Object
# objFeatures = df.select_dtypes(include="object").columns

# #Iterate a loop for features of type object
# from sklearn import preprocessing
# le = preprocessing.LabelEncoder()

# for feat in objFeatures:
#     df[feat] = le.fit_transform(df[feat].astype(str))
 

# df.info()

In [29]:
df.head()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z97,v97,x98,y98,z98,v98,x99,y99,z99,v99
0,0,0.553503,0.589154,-0.053227,0.999848,0.551295,0.617827,-0.098426,0.999913,0.550036,...,0.316258,0.254633,0.504816,0.938543,-0.119085,0.814447,0.494917,0.930861,0.213300,0.267587
1,0,0.55378,0.589641,-0.054581,0.999849,0.551513,0.618255,-0.100107,0.999914,0.550228,...,0.317192,0.255281,0.504461,0.938518,-0.119699,0.814630,0.494285,0.930849,0.213712,0.267646
2,0,0.554106,0.5904,-0.0561,0.999849,0.551763,0.618992,-0.101833,0.999914,0.550453,...,0.317138,0.256015,0.498611,0.938076,-0.121977,0.814902,0.493554,0.930860,0.213213,0.267919
3,0,0.554537,0.591136,-0.056402,0.99985,0.552081,0.619783,-0.102108,0.999915,0.550742,...,0.317088,0.256472,0.495591,0.937631,-0.122727,0.815257,0.492875,0.930846,0.212855,0.267988
4,0,0.554774,0.591698,-0.057988,0.99985,0.552234,0.62037,-0.103818,0.999915,0.550885,...,0.316333,0.256812,0.494406,0.937293,-0.126726,0.815560,0.492563,0.930834,0.211536,0.267697

In [ ]:
# le = LabelEncoder()

# for feat in objFeatures:
#     df[0:] = le.fit_transform(df[0:].astype(str))

In [ ]:
# ## Add these lines to turn off the warnings
# import warnings
# warnings.filterwarnings("ignore")

# ### label encode the categorical values and convert them to numbers 
# le = LabelEncoder()
# # X_train= X_train.loc[:,'x1':]
# # X_train=list(map(str.lower, X_train.columns[:].astype(str)))
# le.fit(X_train['x1'].astype(str))
# X_train['x1'] = le.transform(X_train['x1'].astype(str))
# X_train['x1'] = le.transform(X_train['x1'].astype(str))



# le.fit(X_train['y1'].astype(str))
# X_train['y1'] = le.transform(X_train['y1'].astype(str))
# X_train['y1'] = le.transform(X_train['y1'].astype(str))

# le.fit(X_train['z1'].astype(str))
# X_train['z1'] = le.transform(X_train['z1'].astype(str))
# X_train['z1'] = le.transform(X_train['z1'].astype(str))

# # le.fit(X_train['v1'].astype(str))
# # X_train['v1'] = le.transform(X_train['v1'].astype(str))
# # X_train['v1'] = le.transform(X_train['v1'].astype(str))

In [ ]:
pipelines = {
    'lr':make_pipeline(StandardScaler(), LogisticRegression()),
    'rc':make_pipeline(StandardScaler(), RidgeClassifier()),
    'rf':make_pipeline(StandardScaler(), RandomForestClassifier()),
    'gb':make_pipeline(StandardScaler(), GradientBoostingClassifier()),
}

In [ ]:
pipelines.keys()

In [ ]:
list(pipelines.values())[0]

In [ ]:
lr_model = pipelines['lr']

In [ ]:
lr_model

In [ ]:
lr_train = lr_model.fit(X_train, y_train)

In [ ]:
#this part of code is giving a real problem running these algo
fit_models = {}
for algo, pipeline in pipelines.items():
    model = pipeline.fit(X_train, y_train)
    fit_models[algo] = model

In [ ]:
# from sklearn.preprocessing import LabelEncoder
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.preprocessing import MultiLabelBinarizer


# get `object` columns
# df_object_columns = df.iloc[:, :].select_dtypes(include=['object']).columns
# df_copy_object_columns = df.iloc[:, :].select_dtypes(include=['object']).columns

# le = MultiLabelBinarizer(columns=object_columns)
# instantiate `MultiColumnLabelEncoder`
# mcle = MultiColumnLabelEncoder(columns=object_columns)

# # fit to `df` data
# le.fit(df)

# # transform the `df` data
# le.transform(df)